name: CI Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-no-cyrillic-emoji:
    name: Linting ckeck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check to cyrillic
        run: |
          # Ищем все вхождения кириллицы
          MATCHES=$(grep -RIn "[А-Яа-яЁё]" . || true)
          if [ -n "$MATCHES" ]; then
            echo "::error::Найдены русские буквы (Кириллица) в следующих строках:"
            echo "$MATCHES"
            exit 1
          else
            echo "✔ Кириллица не найдена"
          fi

      - name: Check to emodji
        run: |
          # Диапазоны: Dingbats (галочки/кресты) и основные эмодзи
          EMOJI_PATTERN='[\x{2700}-\x{27BF}\x{1F300}-\x{1F6FF}]'
          MATCHES=$(grep -RInP "$EMOJI_PATTERN" . || true)
          if [ -n "$MATCHES" ]; then
            echo "::error::Найдены эмодзи или символы галочек/крестов в следующих строках:"
            echo "$MATCHES"
            exit 1
          else
            echo "✔ Эмодзи/символы галочек-крестов не найдены"
          fi
