name: CI Lint

on:
  push:
    branches: [dev]
  pull_request:
    

env:
  PYTHON_VERSION: '3.11'

jobs:
  lint-no-cyrillic-emoji:
    runs-on: self-hosted-arm
    container:
      image: ghcr.io/dubovsky-andrey/k8s-ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python3 - << 'EOF'
          import os, sys, regex

          cyr_pattern = regex.compile(r'\p{Cyrillic}')
          emoji_pattern = regex.compile(r'\p{Extended_Pictographic}')
          emoticon_pattern = regex.compile(r'[:;=8][\-~^]?[)(DPp]')

          errors = []
          for root, dirs, files in os.walk('.'):
              for name in files:
                  path = os.path.join(root, name)
                  try:
                      with open(path, encoding='utf-8', errors='ignore') as f:
                          for num, line in enumerate(f, 1):
                              if cyr_pattern.search(line) \
                              or emoji_pattern.search(line) \
                              or emoticon_pattern.search(line):
                                  errors.append(f"{path}:{num}:{line.strip()}")
                  except OSError:
                      continue

          if errors:
              print("Found Cyrillic or emoji in:")
              print("\n".join(errors))
              sys.exit(1)
          else:
              print("✔ No Cyrillic or emoji found")
          EOF
