name: CI Lint

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  lint-no-cyrillic-emoji:
    name: Linting ckeck
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check to cyrillic
        run: |
          MATCHES=$(grep -RInP '\p{Cyrillic}' . || true)
          if [ -n "$MATCHES" ]; then
            echo "::error::Found Cyrillic in the following lines:"
            echo "$MATCHES"
            exit 1
          else
            echo "Cyrillic not found"
          fi

      - name: Check to emodji
        run: |
          # 1) Полный Unicode-блок эмодзи (All emoji/codepoints ChatGPT может вставлять)
          EMOJI='\p{Extended_Pictographic}'

          # 2) Простые текстовые смайлы, например :) ;-P :D
          EMOTICON='[:;=8][\-~^]?[)(DPp]'

          # Объединяем в один паттерн
          PATTERN="($EMOJI|$EMOTICON)"

          MATCH=$(grep -RInP "$PATTERN" . || true)
          if [ -n "$MATCH" ]; then
            echo "::error::Найдены эмодзи или смайлы в следующих строках:"
            echo "$MATCH"
            exit 1
          else
            echo "✔ Эмодзи и смайлы не найдены"
          fi
